import { Inter, Onest } from "next/font/google";
import "./globals.css";
import { ReactLenis } from "@/utils/lenis";
import AOSWrapper from "@/utils/AOSWrapper";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const onest = Onest({ subsets: ["latin"], variable: "--font-onest" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ReactLenis root>
        <body
          className={`${inter.variable} ${onest.variable} font-inter antialiased`}
        >
          <AOSWrapper>{children}</AOSWrapper>
        </body>
      </ReactLenis>
    </html>
  );
}
